### ISSUE TITLE
How do I constrain the gradient fill?

### ISSUE THREAD

**Issue by danchaseCTS** [steffest/DPaint-js#31]
When I draw a square, then try to fill it with a gradient, no matter what I do the gradient covers the entire screen. I also tried using a selection, but that didn't work either. I basically just want to draw a square, and do a gradient within that square but I can't figure out how.

**Comment by danchaseCTS** [comment]
I just realized there's a duplicate to this question, does this mean I need to use a layer and somehow copy the gradient to the other layer?

**Comment by steffest** [comment]
Yes indeed.
I know most (all?) other graphics software only apply drawing actions inside the selection, but for some reason I find it more handy to reverse that: apply a drawing action to a layer and then - if needed - use a selection to cut out the part your need.
I find it handy because then you still can alter/move/resize your drawed part independant from the selection.
Maybe I'll change that behaviour because apparently it seems cumbersome to most users.

So for know:

- make a selection of your square (e.g. with  CTRL-SHIFT-L : select all pixels in layer)
- apply your gradient
- copy the selection to a new layer
- remove original layer


![gradient-fill-rect2](https://github.com/user-attachments/assets/4c6ddf67-6bef-426d-a431-52776ec19924)

**Comment by danchaseCTS** [comment]
Thank you! I'd also like to say I'm impressed by your reply, many on these projects just reply with the equivalent of "Nah", but your explanation is very helpful and refreshing.
